### ISSUE TITLE
[Enhacement] Nmap IPv6 scan

### ISSUE THREAD

**Issue by Hax0rG1rl** [SilverPoision/Rock-ON#2]
Hi, 

Thank for this and your work. Works nice. 

1. Amass too does not install from some whatever reasons. Had to run it through docker. 

2. Would be nice to consider adding the Nmap IPv6 scan too. A lot of cloud-hosted targets are using IPv6 too. 

Currently, the framework returns this:

```
looks like an IPv6 target specification -- you have to use the -6 option.
```

Thanks!

**Comment by SilverPoision** [comment]
First of all Thanks for your kind words and for the problems your are describing ,
1st one is happening because, while installing the script you might not have given the script the right path for the go/bin/amass file.
The solution for this can be, by moving the amass file manually from the go/bin folder to Rock-ON/Tools/ 
And for 2nd one, its in my to do list but as far I will not add more features to this tool because I am already working on its Web UI version that will contain tons of new features.
So you have to wait for it.
