### ISSUE TITLE
Can't find proper area to add keys

### ISSUE THREAD

**Issue by s0meguy1** [SilverPoision/Rock-ON#3]
Hello, for the most part this works great! However I can't find exactly where to add keys for things like shodan. Below are the key errors I keep getting:
![image](https://user-images.githubusercontent.com/25542926/62885453-f33faa00-bd06-11e9-8b8c-48f7773af3b0.png)

I have also set my Censys key in the beginning, but later in the script it says it does not exist. 

Thanks!

**Comment by SilverPoision** [comment]
I am unable to get that for which tool you are taking about in Rock-On because there many tools that require api key and for some I have given the options to just give the api key and it will do the work but for some of them I have given instruction to set them manually, no options to set it in my tool and you have to do it yourself.
If you can make me aware of that from which tool in Rock-ON is giving the output you shown in the screenshot then I can give you the path to set that keys.
Thanks for using Rock-ON and for the feedback
Piyush kumar

**Comment by s0meguy1** [comment]
Ok, I think I know what you mean, but for documentation purposes, I'll ask for these itemsL
shodan
censys
virustotal
riddler

Thanks!

**Comment by s0meguy1** [comment]
Ok I think I figured it out, I was scrolling through the installed go applications and found the README files. Basically you export them into the environment and can edit the ~/.profile and add:
export CENSYS_API_ID=XXXXXXXXXXXXXXX
export CENSYS_API_SECRET=XXXXXXXXXXXXXXXXXXX
export ShodanAPIKey=XXXXXXXXXXXXXXXXX
to the end of it

**Comment by s0meguy1** [comment]
I take that back, exporting then adding to profile did not fix the issue
